### ISSUE TITLE
Docker install fails with error at Composer/SimpleSAML Step

### ISSUE THREAD

**Issue by paulfreeman** [jnyryan/docker-simplesamlphp#2]
I've found this Dockerfile very useful as an exercise in learning Docker and in the process get my head around simpleSAML.  I started with the Docker image available on the Docker hub which saved a lot of time in debugging my iDP. 

I did hit a problem when trying to create my own Dockerfile, and then later discovered that the problem exists here also, so it wasn't just my simpleSAML newbie status. 

When running the install the Composer step that performs the simpleSAML install fails now, presumably due to changes in simpleSAML dependencies since this script was created. 

Here is the output showing the problem 

```
Step 28 : RUN php composer.phar install
 ---> Running in b2c6110c2f1d
PHP Warning:  Module 'mcrypt' already loaded in Unknown on line 0
PHP Warning:  Module 'mcrypt' already loaded in Unknown on line 0
Running composer as root/super user is highly discouraged as packages, plugins and scripts cannot always be trusted
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested PHP extension ext-pdo_sqlite * is missing from your system. Install or enable PHP's pdo_sqlite extension.

The command '/bin/sh -c php composer.phar install' returned a non-zero code: 2
```

**Comment by paulfreeman** [comment]
This may be all that is needed to fix this 

Add to Dockerfile before the Composer run 

`RUN apt-get install -y  php5-sqlite`

**Comment by jnyryan** [comment]
@paulfreeman much appreciated.
I added this in and it's all good.
